name: CI

on:
  push:
    branches:
      - 4.x
      - 5.x
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  testsuite:
    uses: cakephp/.github/.github/workflows/testsuite-with-db.yml@5.x
    secrets: inherit

  cs-stan:
    uses: cakephp/.github/.github/workflows/cs-stan.yml@5.x
    secrets: inherit
